version: "3.9"
services:
  postgres:
    container_name: postgres_keycloak
    image: "postgres:14.5"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    env_file:
      - keycloak-postgres.env
    networks:
      - backend
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_keycloak
    image: "dpage/pgadmin4:5.1"
    env_file:
      - keycloak-postgres.env
    ports:
      - "5050:80"
    networks:
      - backend

  keycloak:
    container_name: keycloak
    image: "quay.io/keycloak/keycloak:19.0.2"
    command: start --optimized
    depends_on:
      - "postgres"
    env_file:
      - keycloak-postgres.env
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge